version: '3.8'

services:
    mysql:
        container_name: mysql-sikerja
        hostname: mysql
        image: mysql:8.0
        ports:
            - '3306:3306'
        environment:
            MYSQL_USER: sikerja
            MYSQL_PASSWORD: sikerja
            MYSQL_DATABASE: sikerja
            MYSQL_ALLOW_EMPTY_PASSWORD: true
        volumes:
            - 'sikerja-db-be:/var/lib/mysql'

volumes:
    sikerja-db-be:
